name: Release
run-name: Release with Rockchip Linux 5.10.160

on:
  workflow_dispatch:

jobs:
  release:
    name: Create release
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create --draft v1.31m3 --title v1.31m3

  build:
    permissions:
        contents: write
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - nanopc-t6

    steps:
      - name: Get more disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev

      - name: cat build-kernel.sh
        shell: bash
        run: cat ./scripts/build-kernel.sh      

      - name: Build image
        shell: bash
        run: sudo ./build.sh -b ${{ matrix.platform }}

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload v1.31m3 ./images/ubuntu-*-preinstalled-*-arm64-${{ matrix.platform }}.*

      - name: show linux kernel git url
        shell: bash
        run: cat ./build/linux-rockchip/.git/config
        
      - name: Clean cache
        shell: bash
        run: sync && sudo rm -rf ./images/ ./build/ && sync
